name = "Etch"
license = "MIT"
licenselink = "https://github.com/edapm/website-theme/blob/master/LICENSE"
description = "Lightweight Hugo theme with a focus on content"
homepage = "https://github.com/edapm/website-theme"
demosite = "https://edwardmason.vercel.app"
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive", "dark mode", "privacy"]
features = ["fast", "blog", "syntax highlighting", "dark mode"]
min_version = "0.41"

[author]
  name = "Lukas Joswiak / Edward Mason"
  homepage = "https://edwardmason.vercel.app"
